services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: essenza_sql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Contra1234
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: ./backend
    container_name: essenza_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://database:1433;databaseName=db_essenza;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Contra1234

  frontend:
    build: ./frontend
    container_name: essenza_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  sqlserver_data: