version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: essenza_sql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Contra1234
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: