spring.datasource.url=jdbc:postgresql://ep-small-glitter-atjodc2f.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oiN6aSkRe3XK
spring.jpa.hibernate.ddl-auto=update
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}